### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by regiscamimura** [Viglino/ol3-games#1]
Hi, thanks for the excelent work. I'm looking at some example pages, https://viglino.github.io/ol3-games/examples/map.sprite.destination.html, and they are not working. It seems some error while importing javascript. The same happens on ol-ext examples for assets animation.

**Comment by Viglino** [comment]
Yes the master full build (ol.js) seems to be buggy.
You have to move to latest build : https://openlayers.org/en/master/build/ol.js > https://openlayers.org/en/latest/build/ol.js
I'll try to change it asap...

**Comment by Viglino** [comment]
Examples are now running well!
Thanks for the feedback!

**Comment by Viglino** [comment]
Examples are now running with the last ol5!

**Comment by regiscamimura** [comment]
Awesome!

**Comment by kuige** [comment]
@Viglino The examples are broken again ! Some assets cannot be loaded. One of the broken demo: https://viglino.github.io/ol-games/examples/map.sprite.path.html 

<img width="433" alt="image" src="https://user-images.githubusercontent.com/8212800/56110431-03c55b00-5f87-11e9-9651-87e2f1737aa4.png">

**Comment by Viglino** [comment]
The example is working fine for me.... Perhaps a problem with rawgit service...
