### ISSUE TITLE
Sprites freezes when scrolling or moving the map

### ISSUE THREAD

**Issue by regiscamimura** [Viglino/ol3-games#2]
When a sprite is moving to a destination or along a path, if you scroll the map or move the map (I mean, drag the map around), the sprite freezes and won't move. When the map zooming/moving stops, the sprite jumps to the point where it should be. This can be see at https://viglino.github.io/ol3-games/examples/map.sprite.destination.html.

When you do the same thing using the feature animation with ol-ext (http://viglino.github.io/ol-ext/examples/animation/map.featureanimation.path.html), that does not happens. Any chances the issue with ol3-games is a easy fix?

**Comment by Viglino** [comment]
FeatureAnimation doesn't modify the feature itself but show an animation on postcompose.
The sprite animation instead modify the feature's geometry but the vector layer doesn't recalculate it when animating/interacting for performance's reasons.
The secret is to use the `updateWhileAnimating: true` and `updateWhileInteracting: true` options on the sprite layer. It will have a performance impact for large amounts of vector data but is good enough for animating some sprites.
I've changed the example and it runs like a charm!

**Comment by regiscamimura** [comment]
Awesome! Thanks, you rock.
